//
//   Copyright (c) 2025 Nick Marino
//   All rights reserved.
//

#version 460

layout(local_size_x = 64) in;

layout(set = 0, binding = 0) readonly buffer BufferAlpha {
    float a[];
};

layout(set = 0, binding = 1) readonly buffer BufferBeta {
    float b[];
};

layout(set = 0, binding = 2) buffer BufferRes {
    float res[];
};

void main() {
    uint i = gl_GlobalInvocationID.x;
    res[i] = a[i] * b[i] + 1.0;
}
